Insert into comunas (nombre_comuna, region_id) values ("Arica	",	1	);
Insert into comunas (nombre_comuna, region_id) values ("Camarones	",	1	);
Insert into comunas (nombre_comuna, region_id) values ("Putre	",	1	);
Insert into comunas (nombre_comuna, region_id) values ("General Lagos	",	1	);
Insert into comunas (nombre_comuna, region_id) values ("Iquique	",	2	);
Insert into comunas (nombre_comuna, region_id) values ("Alto Hospicio	",	2	);
Insert into comunas (nombre_comuna, region_id) values ("Pozo Almonte	",	2	);
Insert into comunas (nombre_comuna, region_id) values ("Camiña	",	2	);
Insert into comunas (nombre_comuna, region_id) values ("Colchane	",	2	);
Insert into comunas (nombre_comuna, region_id) values ("Huara	",	2	);
Insert into comunas (nombre_comuna, region_id) values ("Pica	",	2	);
Insert into comunas (nombre_comuna, region_id) values ("Antofagasta	",	3	);
Insert into comunas (nombre_comuna, region_id) values ("Mejillones	",	3	);
Insert into comunas (nombre_comuna, region_id) values ("Sierra Gorda	",	3	);
Insert into comunas (nombre_comuna, region_id) values ("Taltal	",	3	);
Insert into comunas (nombre_comuna, region_id) values ("Calama	",	3	);
Insert into comunas (nombre_comuna, region_id) values ("Ollagüe	",	3	);
Insert into comunas (nombre_comuna, region_id) values ("San Pedro de Atacama	",	3	);
Insert into comunas (nombre_comuna, region_id) values ("Tocopilla	",	3	);
Insert into comunas (nombre_comuna, region_id) values ("María Elena	",	3	);
Insert into comunas (nombre_comuna, region_id) values ("Copiapó	",	4	);
Insert into comunas (nombre_comuna, region_id) values ("Caldera	",	4	);
Insert into comunas (nombre_comuna, region_id) values ("Tierra Amarilla	",	4	);
Insert into comunas (nombre_comuna, region_id) values ("Chañaral	",	4	);
Insert into comunas (nombre_comuna, region_id) values ("Diego de Almagro	",	4	);
Insert into comunas (nombre_comuna, region_id) values ("Vallenar	",	4	);
Insert into comunas (nombre_comuna, region_id) values ("Alto del Carmen	",	4	);
Insert into comunas (nombre_comuna, region_id) values ("Freirina	",	4	);
Insert into comunas (nombre_comuna, region_id) values ("Huasco	",	4	);
Insert into comunas (nombre_comuna, region_id) values ("La Serena	",	5	);
Insert into comunas (nombre_comuna, region_id) values ("Coquimbo	",	5	);
Insert into comunas (nombre_comuna, region_id) values ("Andacollo	",	5	);
Insert into comunas (nombre_comuna, region_id) values ("La Higuera	",	5	);
Insert into comunas (nombre_comuna, region_id) values ("Paihuano	",	5	);
Insert into comunas (nombre_comuna, region_id) values ("Vicuña	",	5	);
Insert into comunas (nombre_comuna, region_id) values ("Illapel	",	5	);
Insert into comunas (nombre_comuna, region_id) values ("Canela	",	5	);
Insert into comunas (nombre_comuna, region_id) values ("Los Vilos	",	5	);
Insert into comunas (nombre_comuna, region_id) values ("Salamanca	",	5	);
Insert into comunas (nombre_comuna, region_id) values ("Ovalle	",	5	);
Insert into comunas (nombre_comuna, region_id) values ("Combarbalá	",	5	);
Insert into comunas (nombre_comuna, region_id) values ("Monte Patria	",	5	);
Insert into comunas (nombre_comuna, region_id) values ("Punitaqui	",	5	);
Insert into comunas (nombre_comuna, region_id) values ("Río Hurtado	",	5	);
Insert into comunas (nombre_comuna, region_id) values ("Valparaíso	",	6	);
Insert into comunas (nombre_comuna, region_id) values ("Casablanca	",	6	);
Insert into comunas (nombre_comuna, region_id) values ("Concón	",	6	);
Insert into comunas (nombre_comuna, region_id) values ("Juan Fernández	",	6	);
Insert into comunas (nombre_comuna, region_id) values ("Puchuncaví	",	6	);
Insert into comunas (nombre_comuna, region_id) values ("Quintero	",	6	);
Insert into comunas (nombre_comuna, region_id) values ("Viña del Mar	",	6	);
Insert into comunas (nombre_comuna, region_id) values ("Isla de Pascua	",	6	);
Insert into comunas (nombre_comuna, region_id) values ("Los Andes	",	6	);
Insert into comunas (nombre_comuna, region_id) values ("Calle Larga	",	6	);
Insert into comunas (nombre_comuna, region_id) values ("Rinconada	",	6	);
Insert into comunas (nombre_comuna, region_id) values ("San Esteban	",	6	);
Insert into comunas (nombre_comuna, region_id) values ("La Ligua	",	6	);
Insert into comunas (nombre_comuna, region_id) values ("Cabildo	",	6	);
Insert into comunas (nombre_comuna, region_id) values ("Papudo	",	6	);
Insert into comunas (nombre_comuna, region_id) values ("Petorca	",	6	);
Insert into comunas (nombre_comuna, region_id) values ("Zapallar	",	6	);
Insert into comunas (nombre_comuna, region_id) values ("Quillota	",	6	);
Insert into comunas (nombre_comuna, region_id) values ("La Calera	",	6	);
Insert into comunas (nombre_comuna, region_id) values ("Hijuelas	",	6	);
Insert into comunas (nombre_comuna, region_id) values ("La Cruz	",	6	);
Insert into comunas (nombre_comuna, region_id) values ("Nogales	",	6	);
Insert into comunas (nombre_comuna, region_id) values ("San Antonio	",	6	);
Insert into comunas (nombre_comuna, region_id) values ("Algarrobo	",	6	);
Insert into comunas (nombre_comuna, region_id) values ("Cartagena	",	6	);
Insert into comunas (nombre_comuna, region_id) values ("El Quisco	",	6	);
Insert into comunas (nombre_comuna, region_id) values ("El Tabo	",	6	);
Insert into comunas (nombre_comuna, region_id) values ("Santo Domingo	",	6	);
Insert into comunas (nombre_comuna, region_id) values ("San Felipe	",	6	);
Insert into comunas (nombre_comuna, region_id) values ("Catemu	",	6	);
Insert into comunas (nombre_comuna, region_id) values ("Llay-Llay	",	6	);
Insert into comunas (nombre_comuna, region_id) values ("Panquehue	",	6	);
Insert into comunas (nombre_comuna, region_id) values ("Putaendo	",	6	);
Insert into comunas (nombre_comuna, region_id) values ("Santa María	",	6	);
Insert into comunas (nombre_comuna, region_id) values ("Quilpué	",	6	);
Insert into comunas (nombre_comuna, region_id) values ("Limache	",	6	);
Insert into comunas (nombre_comuna, region_id) values ("Olmué	",	6	);
Insert into comunas (nombre_comuna, region_id) values ("Villa Alemana	",	6	);
Insert into comunas (nombre_comuna, region_id) values ("Rancagua	",	8	);
Insert into comunas (nombre_comuna, region_id) values ("Codegua	",	8	);
Insert into comunas (nombre_comuna, region_id) values ("Coinco	",	8	);
Insert into comunas (nombre_comuna, region_id) values ("Coltauco	",	8	);
Insert into comunas (nombre_comuna, region_id) values ("Doñihue	",	8	);
Insert into comunas (nombre_comuna, region_id) values ("Graneros	",	8	);
Insert into comunas (nombre_comuna, region_id) values ("Las Cabras	",	8	);
Insert into comunas (nombre_comuna, region_id) values ("Machalí	",	8	);
Insert into comunas (nombre_comuna, region_id) values ("Malloa	",	8	);
Insert into comunas (nombre_comuna, region_id) values ("Mostazal	",	8	);
Insert into comunas (nombre_comuna, region_id) values ("Olivar	",	8	);
Insert into comunas (nombre_comuna, region_id) values ("Peumo	",	8	);
Insert into comunas (nombre_comuna, region_id) values ("Pichidegua	",	8	);
Insert into comunas (nombre_comuna, region_id) values ("Quinta de Tilcoco	",	8	);
Insert into comunas (nombre_comuna, region_id) values ("Rengo	",	8	);
Insert into comunas (nombre_comuna, region_id) values ("Requínoa	",	8	);
Insert into comunas (nombre_comuna, region_id) values ("San Vicente	",	8	);
Insert into comunas (nombre_comuna, region_id) values ("Pichilemu	",	8	);
Insert into comunas (nombre_comuna, region_id) values ("La Estrella	",	8	);
Insert into comunas (nombre_comuna, region_id) values ("Litueche	",	8	);
Insert into comunas (nombre_comuna, region_id) values ("Marchihue	",	8	);
Insert into comunas (nombre_comuna, region_id) values ("Navidad	",	8	);
Insert into comunas (nombre_comuna, region_id) values ("Paredones	",	8	);
Insert into comunas (nombre_comuna, region_id) values ("San Fernando	",	8	);
Insert into comunas (nombre_comuna, region_id) values ("Chépica	",	8	);
Insert into comunas (nombre_comuna, region_id) values ("Chimbarongo	",	8	);
Insert into comunas (nombre_comuna, region_id) values ("Lolol	",	8	);
Insert into comunas (nombre_comuna, region_id) values ("Nancagua	",	8	);
Insert into comunas (nombre_comuna, region_id) values ("Palmilla	",	8	);
Insert into comunas (nombre_comuna, region_id) values ("Peralillo	",	8	);
Insert into comunas (nombre_comuna, region_id) values ("Placilla	",	8	);
Insert into comunas (nombre_comuna, region_id) values ("Pumanque	",	8	);
Insert into comunas (nombre_comuna, region_id) values ("Santa Cruz	",	8	);
Insert into comunas (nombre_comuna, region_id) values ("Talca	",	9	);
Insert into comunas (nombre_comuna, region_id) values ("Constitución	",	9	);
Insert into comunas (nombre_comuna, region_id) values ("Curepto	",	9	);
Insert into comunas (nombre_comuna, region_id) values ("Empedrado	",	9	);
Insert into comunas (nombre_comuna, region_id) values ("Maule	",	9	);
Insert into comunas (nombre_comuna, region_id) values ("Pelarco	",	9	);
Insert into comunas (nombre_comuna, region_id) values ("Pencahue	",	9	);
Insert into comunas (nombre_comuna, region_id) values ("Río Claro	",	9	);
Insert into comunas (nombre_comuna, region_id) values ("San Clemente	",	9	);
Insert into comunas (nombre_comuna, region_id) values ("San Rafael	",	9	);
Insert into comunas (nombre_comuna, region_id) values ("Cauquenes	",	9	);
Insert into comunas (nombre_comuna, region_id) values ("Chanco	",	9	);
Insert into comunas (nombre_comuna, region_id) values ("Pelluhue	",	9	);
Insert into comunas (nombre_comuna, region_id) values ("Curicó	",	9	);
Insert into comunas (nombre_comuna, region_id) values ("Hualañé	",	9	);
Insert into comunas (nombre_comuna, region_id) values ("Licantén	",	9	);
Insert into comunas (nombre_comuna, region_id) values ("Molina	",	9	);
Insert into comunas (nombre_comuna, region_id) values ("Rauco	",	9	);
Insert into comunas (nombre_comuna, region_id) values ("Romeral	",	9	);
Insert into comunas (nombre_comuna, region_id) values ("Sagrada Familia	",	9	);
Insert into comunas (nombre_comuna, region_id) values ("Teno	",	9	);
Insert into comunas (nombre_comuna, region_id) values ("Vichuquén	",	9	);
Insert into comunas (nombre_comuna, region_id) values ("Linares	",	9	);
Insert into comunas (nombre_comuna, region_id) values ("Colbún	",	9	);
Insert into comunas (nombre_comuna, region_id) values ("Longaví	",	9	);
Insert into comunas (nombre_comuna, region_id) values ("Parral	",	9	);
Insert into comunas (nombre_comuna, region_id) values ("Retiro	",	9	);
Insert into comunas (nombre_comuna, region_id) values ("San Javier	",	9	);
Insert into comunas (nombre_comuna, region_id) values ("Villa Alegre	",	9	);
Insert into comunas (nombre_comuna, region_id) values ("Yerbas Buenas	",	9	);
Insert into comunas (nombre_comuna, region_id) values ("Chillán	",	10	);
Insert into comunas (nombre_comuna, region_id) values ("Bulnes	",	10	);
Insert into comunas (nombre_comuna, region_id) values ("Chillán Viejo	",	10	);
Insert into comunas (nombre_comuna, region_id) values ("El Carmen	",	10	);
Insert into comunas (nombre_comuna, region_id) values ("Pemuco	",	10	);
Insert into comunas (nombre_comuna, region_id) values ("Pinto	",	10	);
Insert into comunas (nombre_comuna, region_id) values ("Quillón	",	10	);
Insert into comunas (nombre_comuna, region_id) values ("San Ignacio	",	10	);
Insert into comunas (nombre_comuna, region_id) values ("Yungay	",	10	);
Insert into comunas (nombre_comuna, region_id) values ("Quirihue	",	10	);
Insert into comunas (nombre_comuna, region_id) values ("Cobquecura	",	10	);
Insert into comunas (nombre_comuna, region_id) values ("Coelemu	",	10	);
Insert into comunas (nombre_comuna, region_id) values ("Ninhue	",	10	);
Insert into comunas (nombre_comuna, region_id) values ("Portezuelo	",	10	);
Insert into comunas (nombre_comuna, region_id) values ("Ránquil	",	10	);
Insert into comunas (nombre_comuna, region_id) values ("Treguaco	",	10	);
Insert into comunas (nombre_comuna, region_id) values ("San Carlos	",	10	);
Insert into comunas (nombre_comuna, region_id) values ("Coihueco	",	10	);
Insert into comunas (nombre_comuna, region_id) values ("Ñiquén	",	10	);
Insert into comunas (nombre_comuna, region_id) values ("San Fabián	",	10	);
Insert into comunas (nombre_comuna, region_id) values ("San Nicolás	",	10	);
Insert into comunas (nombre_comuna, region_id) values ("Concepción	",	11	);
Insert into comunas (nombre_comuna, region_id) values ("Coronel	",	11	);
Insert into comunas (nombre_comuna, region_id) values ("Chiguayante	",	11	);
Insert into comunas (nombre_comuna, region_id) values ("Florida	",	11	);
Insert into comunas (nombre_comuna, region_id) values ("Hualqui	",	11	);
Insert into comunas (nombre_comuna, region_id) values ("Lota	",	11	);
Insert into comunas (nombre_comuna, region_id) values ("Penco	",	11	);
Insert into comunas (nombre_comuna, region_id) values ("San Pedro de La Paz	",	11	);
Insert into comunas (nombre_comuna, region_id) values ("Santa Juana	",	11	);
Insert into comunas (nombre_comuna, region_id) values ("Talcahuano	",	11	);
Insert into comunas (nombre_comuna, region_id) values ("Tomé	",	11	);
Insert into comunas (nombre_comuna, region_id) values ("Hualpén	",	11	);
Insert into comunas (nombre_comuna, region_id) values ("Lebu	",	11	);
Insert into comunas (nombre_comuna, region_id) values ("Arauco	",	11	);
Insert into comunas (nombre_comuna, region_id) values ("Cañete	",	11	);
Insert into comunas (nombre_comuna, region_id) values ("Contulmo	",	11	);
Insert into comunas (nombre_comuna, region_id) values ("Curanilahue	",	11	);
Insert into comunas (nombre_comuna, region_id) values ("Los Álamos	",	11	);
Insert into comunas (nombre_comuna, region_id) values ("Tirúa	",	11	);
Insert into comunas (nombre_comuna, region_id) values ("Los Ángeles	",	11	);
Insert into comunas (nombre_comuna, region_id) values ("Antuco	",	11	);
Insert into comunas (nombre_comuna, region_id) values ("Cabrero	",	11	);
Insert into comunas (nombre_comuna, region_id) values ("Laja	",	11	);
Insert into comunas (nombre_comuna, region_id) values ("Mulchén	",	11	);
Insert into comunas (nombre_comuna, region_id) values ("Nacimiento	",	11	);
Insert into comunas (nombre_comuna, region_id) values ("Negrete	",	11	);
Insert into comunas (nombre_comuna, region_id) values ("Quilaco	",	11	);
Insert into comunas (nombre_comuna, region_id) values ("Quilleco	",	11	);
Insert into comunas (nombre_comuna, region_id) values ("San Rosendo	",	11	);
Insert into comunas (nombre_comuna, region_id) values ("Santa Bárbara	",	11	);
Insert into comunas (nombre_comuna, region_id) values ("Tucapel	",	11	);
Insert into comunas (nombre_comuna, region_id) values ("Yumbel	",	11	);
Insert into comunas (nombre_comuna, region_id) values ("Alto Biobío	",	11	);
Insert into comunas (nombre_comuna, region_id) values ("Temuco	",	12	);
Insert into comunas (nombre_comuna, region_id) values ("Carahue	",	12	);
Insert into comunas (nombre_comuna, region_id) values ("Cunco	",	12	);
Insert into comunas (nombre_comuna, region_id) values ("Curarrehue	",	12	);
Insert into comunas (nombre_comuna, region_id) values ("Freire	",	12	);
Insert into comunas (nombre_comuna, region_id) values ("Galvarino	",	12	);
Insert into comunas (nombre_comuna, region_id) values ("Gorbea	",	12	);
Insert into comunas (nombre_comuna, region_id) values ("Lautaro	",	12	);
Insert into comunas (nombre_comuna, region_id) values ("Loncoche	",	12	);
Insert into comunas (nombre_comuna, region_id) values ("Melipeuco	",	12	);
Insert into comunas (nombre_comuna, region_id) values ("Nueva Imperial	",	12	);
Insert into comunas (nombre_comuna, region_id) values ("Padre Las Casas	",	12	);
Insert into comunas (nombre_comuna, region_id) values ("Perquenco	",	12	);
Insert into comunas (nombre_comuna, region_id) values ("Pitrufquén	",	12	);
Insert into comunas (nombre_comuna, region_id) values ("Pucón	",	12	);
Insert into comunas (nombre_comuna, region_id) values ("Saavedra	",	12	);
Insert into comunas (nombre_comuna, region_id) values ("Teodoro Schmidt	",	12	);
Insert into comunas (nombre_comuna, region_id) values ("Toltén	",	12	);
Insert into comunas (nombre_comuna, region_id) values ("Vilcún	",	12	);
Insert into comunas (nombre_comuna, region_id) values ("Villarrica	",	12	);
Insert into comunas (nombre_comuna, region_id) values ("Cholchol	",	12	);
Insert into comunas (nombre_comuna, region_id) values ("Angol	",	12	);
Insert into comunas (nombre_comuna, region_id) values ("Collipulli	",	12	);
Insert into comunas (nombre_comuna, region_id) values ("Curacautín	",	12	);
Insert into comunas (nombre_comuna, region_id) values ("Ercilla	",	12	);
Insert into comunas (nombre_comuna, region_id) values ("Lonquimay	",	12	);
Insert into comunas (nombre_comuna, region_id) values ("Los Sauces	",	12	);
Insert into comunas (nombre_comuna, region_id) values ("Lumaco	",	12	);
Insert into comunas (nombre_comuna, region_id) values ("Purén	",	12	);
Insert into comunas (nombre_comuna, region_id) values ("Renaico	",	12	);
Insert into comunas (nombre_comuna, region_id) values ("Traiguén	",	12	);
Insert into comunas (nombre_comuna, region_id) values ("Victoria	",	12	);
Insert into comunas (nombre_comuna, region_id) values ("Valdivia	",	13	);
Insert into comunas (nombre_comuna, region_id) values ("Corral	",	13	);
Insert into comunas (nombre_comuna, region_id) values ("Lanco	",	13	);
Insert into comunas (nombre_comuna, region_id) values ("Los Lagos	",	13	);
Insert into comunas (nombre_comuna, region_id) values ("Máfil	",	13	);
Insert into comunas (nombre_comuna, region_id) values ("Mariquina	",	13	);
Insert into comunas (nombre_comuna, region_id) values ("Paillaco	",	13	);
Insert into comunas (nombre_comuna, region_id) values ("Panguipulli	",	13	);
Insert into comunas (nombre_comuna, region_id) values ("La Unión	",	13	);
Insert into comunas (nombre_comuna, region_id) values ("Futrono	",	13	);
Insert into comunas (nombre_comuna, region_id) values ("Lago Ranco	",	13	);
Insert into comunas (nombre_comuna, region_id) values ("Río Bueno	",	13	);
Insert into comunas (nombre_comuna, region_id) values ("Puerto Montt	",	14	);
Insert into comunas (nombre_comuna, region_id) values ("Calbuco	",	14	);
Insert into comunas (nombre_comuna, region_id) values ("Cochamó	",	14	);
Insert into comunas (nombre_comuna, region_id) values ("Fresia	",	14	);
Insert into comunas (nombre_comuna, region_id) values ("Frutillar	",	14	);
Insert into comunas (nombre_comuna, region_id) values ("Los Muermos	",	14	);
Insert into comunas (nombre_comuna, region_id) values ("Llanquihue	",	14	);
Insert into comunas (nombre_comuna, region_id) values ("Maullín	",	14	);
Insert into comunas (nombre_comuna, region_id) values ("Puerto Varas	",	14	);
Insert into comunas (nombre_comuna, region_id) values ("Castro	",	14	);
Insert into comunas (nombre_comuna, region_id) values ("Ancud	",	14	);
Insert into comunas (nombre_comuna, region_id) values ("Chonchi	",	14	);
Insert into comunas (nombre_comuna, region_id) values ("Curaco de Vélez	",	14	);
Insert into comunas (nombre_comuna, region_id) values ("Dalcahue	",	14	);
Insert into comunas (nombre_comuna, region_id) values ("Puqueldón	",	14	);
Insert into comunas (nombre_comuna, region_id) values ("Queilén	",	14	);
Insert into comunas (nombre_comuna, region_id) values ("Quellón	",	14	);
Insert into comunas (nombre_comuna, region_id) values ("Quemchi	",	14	);
Insert into comunas (nombre_comuna, region_id) values ("Quinchao	",	14	);
Insert into comunas (nombre_comuna, region_id) values ("Osorno	",	14	);
Insert into comunas (nombre_comuna, region_id) values ("Puerto Octay	",	14	);
Insert into comunas (nombre_comuna, region_id) values ("Purranque	",	14	);
Insert into comunas (nombre_comuna, region_id) values ("Puyehue	",	14	);
Insert into comunas (nombre_comuna, region_id) values ("Río Negro	",	14	);
Insert into comunas (nombre_comuna, region_id) values ("San Juan de la Costa	",	14	);
Insert into comunas (nombre_comuna, region_id) values ("San Pablo	",	14	);
Insert into comunas (nombre_comuna, region_id) values ("Chaitén	",	14	);
Insert into comunas (nombre_comuna, region_id) values ("Futaleufú	",	14	);
Insert into comunas (nombre_comuna, region_id) values ("Hualaihué	",	14	);
Insert into comunas (nombre_comuna, region_id) values ("Palena	",	14	);
Insert into comunas (nombre_comuna, region_id) values ("Coyhaique	",	15	);
Insert into comunas (nombre_comuna, region_id) values ("Lago Verde	",	15	);
Insert into comunas (nombre_comuna, region_id) values ("Aysén	",	15	);
Insert into comunas (nombre_comuna, region_id) values ("Cisnes	",	15	);
Insert into comunas (nombre_comuna, region_id) values ("Guaitecas	",	15	);
Insert into comunas (nombre_comuna, region_id) values ("Cochrane	",	15	);
Insert into comunas (nombre_comuna, region_id) values ("O'Higgins	",	15	);
Insert into comunas (nombre_comuna, region_id) values ("Tortel	",	15	);
Insert into comunas (nombre_comuna, region_id) values ("Chile Chico	",	15	);
Insert into comunas (nombre_comuna, region_id) values ("Río Ibáñez	",	15	);
Insert into comunas (nombre_comuna, region_id) values ("Punta Arenas	",	16	);
Insert into comunas (nombre_comuna, region_id) values ("Laguna Blanca	",	16	);
Insert into comunas (nombre_comuna, region_id) values ("Río Verde	",	16	);
Insert into comunas (nombre_comuna, region_id) values ("San Gregorio	",	16	);
Insert into comunas (nombre_comuna, region_id) values ("Cabo de Hornos	",	16	);
Insert into comunas (nombre_comuna, region_id) values ("Antártica	",	16	);
Insert into comunas (nombre_comuna, region_id) values ("Porvenir	",	16	);
Insert into comunas (nombre_comuna, region_id) values ("Primavera	",	16	);
Insert into comunas (nombre_comuna, region_id) values ("Timaukel	",	16	);
Insert into comunas (nombre_comuna, region_id) values ("Natales	",	16	);
Insert into comunas (nombre_comuna, region_id) values ("Torres del Paine	",	16	);
Insert into comunas (nombre_comuna, region_id) values ("Santiago	",	7	);
Insert into comunas (nombre_comuna, region_id) values ("Cerrillos	",	7	);
Insert into comunas (nombre_comuna, region_id) values ("Cerro Navia	",	7	);
Insert into comunas (nombre_comuna, region_id) values ("Conchalí	",	7	);
Insert into comunas (nombre_comuna, region_id) values ("El Bosque	",	7	);
Insert into comunas (nombre_comuna, region_id) values ("Estación Central	",	7	);
Insert into comunas (nombre_comuna, region_id) values ("Huechuraba	",	7	);
Insert into comunas (nombre_comuna, region_id) values ("Independencia	",	7	);
Insert into comunas (nombre_comuna, region_id) values ("La Cisterna	",	7	);
Insert into comunas (nombre_comuna, region_id) values ("La Florida	",	7	);
Insert into comunas (nombre_comuna, region_id) values ("La Granja	",	7	);
Insert into comunas (nombre_comuna, region_id) values ("La Pintana	",	7	);
Insert into comunas (nombre_comuna, region_id) values ("La Reina	",	7	);
Insert into comunas (nombre_comuna, region_id) values ("Las Condes	",	7	);
Insert into comunas (nombre_comuna, region_id) values ("Lo Barnechea	",	7	);
Insert into comunas (nombre_comuna, region_id) values ("Lo Espejo	",	7	);
Insert into comunas (nombre_comuna, region_id) values ("Lo Prado	",	7	);
Insert into comunas (nombre_comuna, region_id) values ("Macul	",	7	);
Insert into comunas (nombre_comuna, region_id) values ("Maipú	",	7	);
Insert into comunas (nombre_comuna, region_id) values ("Ñuñoa	",	7	);
Insert into comunas (nombre_comuna, region_id) values ("Pedro Aguirre Cerda	",	7	);
Insert into comunas (nombre_comuna, region_id) values ("Peñalolén	",	7	);
Insert into comunas (nombre_comuna, region_id) values ("Providencia	",	7	);
Insert into comunas (nombre_comuna, region_id) values ("Pudahuel	",	7	);
Insert into comunas (nombre_comuna, region_id) values ("Quilicura	",	7	);
Insert into comunas (nombre_comuna, region_id) values ("Quinta Normal	",	7	);
Insert into comunas (nombre_comuna, region_id) values ("Recoleta	",	7	);
Insert into comunas (nombre_comuna, region_id) values ("Renca	",	7	);
Insert into comunas (nombre_comuna, region_id) values ("San Joaquín	",	7	);
Insert into comunas (nombre_comuna, region_id) values ("San Miguel	",	7	);
Insert into comunas (nombre_comuna, region_id) values ("San Ramón	",	7	);
Insert into comunas (nombre_comuna, region_id) values ("Vitacura	",	7	);
Insert into comunas (nombre_comuna, region_id) values ("Puente Alto	",	7	);
Insert into comunas (nombre_comuna, region_id) values ("Pirque	",	7	);
Insert into comunas (nombre_comuna, region_id) values ("San José de Maipo	",	7	);
Insert into comunas (nombre_comuna, region_id) values ("Colina	",	7	);
Insert into comunas (nombre_comuna, region_id) values ("Lampa	",	7	);
Insert into comunas (nombre_comuna, region_id) values ("Til Til	",	7	);
Insert into comunas (nombre_comuna, region_id) values ("San Bernardo	",	7	);
Insert into comunas (nombre_comuna, region_id) values ("Buin	",	7	);
Insert into comunas (nombre_comuna, region_id) values ("Calera de Tango	",	7	);
Insert into comunas (nombre_comuna, region_id) values ("Paine	",	7	);
Insert into comunas (nombre_comuna, region_id) values ("Melipilla	",	7	);
Insert into comunas (nombre_comuna, region_id) values ("Alhué	",	7	);
Insert into comunas (nombre_comuna, region_id) values ("Curacaví	",	7	);
Insert into comunas (nombre_comuna, region_id) values ("María Pinto	",	7	);
Insert into comunas (nombre_comuna, region_id) values ("San Pedro	",	7	);
Insert into comunas (nombre_comuna, region_id) values ("Talagante	",	7	);
Insert into comunas (nombre_comuna, region_id) values ("El Monte	",	7	);
Insert into comunas (nombre_comuna, region_id) values ("Isla de Maipo	",	7	);
Insert into comunas (nombre_comuna, region_id) values ("Padre Hurtado	",	7	);
Insert into comunas (nombre_comuna, region_id) values ("Peñaflor	",	7	);

UPDATE comunas SET nombre_comuna = TRIM(nombre_comuna);

/*
Activar para aplicar trim a todos los valores
SET SQL_SAFE_UPDATES = 0;
desactivar cuando se utilize el trim masivo
SET SQL_SAFE_UPDATES = 1;
*/

